### ISSUE TITLE
node 14 import error

### ISSUE THREAD

**Issue by mattgodbolt** [words/profanities#21]
Hi, we're using `node.js`  v14.x with `esm: true`, but when we `import` profanities v3.0.0 we get:

```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/matthew/dev/ce/compiler-explorer/node_modules/profanities/index.js
require() of ES modules is not supported.
require() of /home/matthew/dev/ce/compiler-explorer/node_modules/profanities/index.js from /home/matthew/dev/ce/compiler-explorer/lib/storage/base.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /home/matthew/dev/ce/compiler-explorer/node_modules/profanities/package.json.

    at new NodeError (internal/errors.js:322:7)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1102:13) {
  code: 'ERR_REQUIRE_ESM'
}
```

The same worked ok with profanities `2.14.0`.  The offending line in our code does /not/ use `require`, despite the error:

```js
import { profanities } from 'profanities';
```

(see https://github.com/compiler-explorer/compiler-explorer/blob/b3521cc1ec217db7294316dd919e86876575654a/lib/storage/base.js#L25 which has the code for v2.14.0 checked in)

**Comment by mattgodbolt** [comment]
It seems to be that, and unrelated to profanities. Apologies for the noise.
